// import { ClothingCategory, ClothingItem, Gender } from "@/interfaces/Clothes";

export const productsData: any[] = [
  {
    id: 1,
    name: "Camiseta Básica",
    brand: "XYZ Moda",
    price: 19.99,
    oldPrice: 29.99,
    sizes: ["S", "M", "L", "XL"],
    color: ["white"],
    category: "Tops",
    gender: "F",
    inStock: true,
    description:
      "Esta camiseta básica branca feminina é a peça essencial que não pode faltar no seu guarda-roupa. Perfeita para combinar com qualquer look, desde jeans até saias. Feita com algodão de alta qualidade, proporciona conforto durante todo o dia. A modelagem é pensada para valorizar as curvas femininas, garantindo um ajuste perfeito. Cuide dela lavando à máquina em água fria e secando em temperatura baixa. Adquira esta camiseta e tenha versatilidade e estilo no seu dia a dia.",
    image: "/images/product-01.jpg",
    materials: ["Algodão"],
    careInstructions: [
      "Lavar à máquina em água fria",
      "Secar em temperatura baixa",
    ],
    reviews: [
      {
        id: 3,
        userId: 789,
        rating: 4.8,
        comment: "Camiseta confortável e de ótima qualidade!",
        createdAt: new Date(),
      },
      {
        id: 4,
        userId: 101,
        rating: 4.0,
        comment: "Adorei a versatilidade desta camiseta.",
        createdAt: new Date(),
      },
    ],
    rating: 4.4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    name: "Camisa Social",
    brand: "Aristocracia Moda",
    price: 49.99,
    oldPrice: 59.99,
    sizes: ["S", "M", "L", "XL"],
    color: ["white"],
    category: "Camisas Sociais",
    gender: "F",
    inStock: true,
    description:
      "Esta camisa social branca feminina é a escolha perfeita para ocasiões formais e elegantes. Feita com tecido de alta qualidade, esta camisa proporciona conforto e um ajuste impecável. O design clássico e atemporal, tornando-a a opção ideal para reuniões de negócios, casamentos e eventos especiais. Cuide dela lavando à máquina em água fria e secando em temperatura baixa. Adquira esta camisa social e adicione sofisticação ao seu guarda-roupa.",
    image: "/images/product-02.jpg",
    materials: ["Algodão"],
    careInstructions: [
      "Lavar à máquina em água fria",
      "Secar em temperatura baixa",
      "Passar a ferro em temperatura média",
    ],
    reviews: [
      {
        id: 5,
        userId: 222,
        rating: 4.9,
        comment: "Uma camisa social de alta qualidade!",
        createdAt: new Date(),
      },
      {
        id: 6,
        userId: 333,
        rating: 4.5,
        comment: "Excelente para eventos formais.",
        createdAt: new Date(),
      },
    ],
    rating: 4.7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    name: "Camiseta Xadrez Azul",
    brand: "StreetStyle",
    price: 34.99,
    oldPrice: 44.99,
    sizes: ["S", "M", "L", "XL"],
    color: ["blue", "white"],
    category: "Camisetas",
    gender: "M",
    inStock: true,
    description:
      "Esta camiseta xadrez azul masculina é uma escolha estilosa para um visual casual e descontraído. O padrão xadrez em tons de azul e branco adiciona um toque de estilo à sua roupa. Feita com algodão de alta qualidade, esta camiseta oferece conforto durante todo o dia. Ela combina perfeitamente com jeans ou bermudas para um look descontraído e moderno. Cuide dela lavando à máquina em água fria e secando em temperatura baixa. Adquira esta camiseta xadrez para um visual despojado e elegante.",
    image: "/images/product-03.jpg",
    materials: ["Algodão"],
    careInstructions: [
      "Lavar à máquina em água fria",
      "Secar em temperatura baixa",
    ],
    reviews: [
      {
        id: 7,
        userId: 444,
        rating: 4.7,
        comment: "Ótima camiseta para um estilo casual.",
        createdAt: new Date(),
      },
      {
        id: 8,
        userId: 555,
        rating: 4.2,
        comment: "O xadrez dá um toque especial a esta camiseta.",
        createdAt: new Date(),
      },
    ],
    rating: 4.5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    name: "Casaco Clássico Bege",
    brand: "Fashion Elegance",
    price: 99.99,
    oldPrice: 129.99,
    sizes: ["S", "M", "L", "XL"],
    color: ["beige"],
    category: "Casacos",
    gender: "Unisex",
    inStock: true,
    description:
      "Este casaco clássico bege é uma peça atemporal que adiciona elegância ao seu guarda-roupa. Feito com materiais de alta qualidade, este casaco oferece conforto e estilo. O corte clássico e a cor neutra tornam-no adequado para todas as ocasiões, desde reuniões de negócios até eventos sociais. Este casaco é um investimento duradouro para o seu guarda-roupa de inverno. Cuide dele lavando à máquina em água fria e secando em temperatura baixa. Adquira este casaco clássico e faça uma declaração de estilo duradoura.",
    image: "/images/product-04.jpg",
    materials: ["Lã", "Poliéster"],
    careInstructions: [
      "Lavar à máquina em água fria",
      "Secar em temperatura baixa",
      "Passar a ferro em temperatura média",
    ],
    reviews: [
      {
        id: 9,
        userId: 666,
        rating: 4.9,
        comment: "Um casaco elegante e quente para o inverno.",
        createdAt: new Date(),
      },
      {
        id: 10,
        userId: 777,
        rating: 4.7,
        comment: "Ótimo ajuste e qualidade.",
        createdAt: new Date(),
      },
    ],
    rating: 4.8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    name: "Saia Jeans Escura",
    brand: "Denim Style",
    price: 39.99,
    oldPrice: 49.99,
    sizes: ["S", "M", "L"],
    color: ["dark blue"],
    category: "Saias",
    gender: "F",
    inStock: true,
    description:
      "Esta saia jeans escura é a escolha perfeita para um visual casual e elegante. Feita com denim de alta qualidade, esta saia oferece conforto e durabilidade. O tom de azul escuro é versátil e combina bem com diferentes tipos de blusas e sapatos. Com um corte moderno e detalhes de costura, esta saia adiciona estilo ao seu look diário. Combine com botas ou tênis para um visual descontraído ou com saltos para uma ocasião mais formal. Cuide dela lavando à máquina em água fria e secando em temperatura baixa. Adquira esta saia jeans escura e tenha uma peça versátil em seu guarda-roupa.",
    image: "/images/product-05.jpg",
    materials: ["Denim"],
    careInstructions: [
      "Lavar à máquina em água fria",
      "Secar em temperatura baixa",
    ],
    reviews: [
      {
        id: 11,
        userId: 888,
        rating: 4.6,
        comment: "A saia jeans perfeita para qualquer ocasião!",
        createdAt: new Date(),
      },
      {
        id: 12,
        userId: 999,
        rating: 4.3,
        comment: "Adorei o ajuste desta saia.",
        createdAt: new Date(),
      },
    ],
    rating: 4.45,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    name: "Relógio Clássico Vintage",
    brand: "Timeless Collectibles",
    price: 149.99,
    oldPrice: 199.99,
    color: ["silver"],
    category: "Relógios",
    gender: "Unisex",
    inStock: true,
    description:
      "Este relógio clássico vintage é uma verdadeira joia para os amantes de estilo e elegância atemporais. Com um design vintage inspirado na era dourada da relojoaria, este relógio apresenta uma caixa de metal prateada com detalhes em ouro. O mostrador branco com números romanos adiciona um toque de sofisticação. O movimento mecânico preciso mantém o tempo com precisão. A pulseira de couro genuíno é confortável de usar e envelhece lindamente com o tempo. Este relógio é perfeito para ocasiões especiais ou para quem aprecia a estética clássica. Adquira este relógio vintage e adicione um toque de nostalgia ao seu estilo.",
    image: "/images/product-06.jpg",
    materials: ["Metal", "Couro"],
    dimensions: "Diâmetro da caixa: 40mm",
    waterResistance: "Resistente a respingos de água",
    reviews: [
      {
        id: 13,
        userId: 111,
        rating: 4.9,
        comment: "Um relógio vintage incrível, parece uma obra de arte!",
        createdAt: new Date(),
      },
      {
        id: 14,
        userId: 222,
        rating: 4.7,
        comment: "O couro da pulseira é muito confortável.",
        createdAt: new Date(),
      },
    ],
    rating: 4.8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    name: "Blazer Feminino Escuro",
    brand: "Elegância Moderna",
    price: 79.99,
    oldPrice: 99.99,
    sizes: ["S", "M", "L", "XL"],
    color: ["dark navy"],
    category: "Blazers",
    gender: "F",
    inStock: true,
    description:
      "Este blazer feminino escuro é a peça essencial para o seu guarda-roupa profissional e elegante. Com um corte moderno e sofisticado, este blazer é perfeito para reuniões de negócios, entrevistas de emprego e eventos formais. O tom de azul-marinho escuro é versátil e combina bem com diferentes roupas. Feito com tecido de alta qualidade, proporciona conforto e um ajuste elegante. Combine com calças sociais ou uma saia para um visual impecável. Cuide dele lavando à seco para manter a sua aparência impecável. Adquira este blazer e eleve o seu estilo profissional.",
    image: "/images/product-07.jpg",
    materials: ["Poliéster", "Viscose", "Elastano"],
    careInstructions: [
      "Lavagem a seco recomendada",
      "Não lavar na máquina",
      "Passar a ferro em temperatura baixa",
    ],
    reviews: [
      {
        id: 15,
        userId: 333,
        rating: 4.8,
        comment: "Um blazer elegante e bem ajustado.",
        createdAt: new Date(),
      },
      {
        id: 16,
        userId: 444,
        rating: 4.5,
        comment: "Adorei a qualidade deste blazer.",
        createdAt: new Date(),
      },
    ],
    rating: 4.65,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    name: "Camiseta Feminina Estampada",
    brand: "Fashion Prints",
    price: 29.99,
    oldPrice: 39.99,
    sizes: ["S", "M", "L"],
    color: ["white", "blue", "pink"],
    category: "Camisetas",
    gender: "F",
    inStock: true,
    description:
      "Esta camiseta feminina estampada é uma adição divertida e elegante ao seu guarda-roupa. Com uma variedade de estampas disponíveis, esta camiseta permite que você expresse seu estilo único. Feita com algodão macio de alta qualidade, oferece conforto durante todo o dia. O corte moderno garante um ajuste perfeito. Esta camiseta é perfeita para combinar com jeans ou shorts para um look descontraído. Cuide dela lavando à máquina em água fria e secando em temperatura baixa. Adquira esta camiseta estampada e adicione um toque de diversão ao seu visual diário.",
    image: "/images/product-08.jpg",
    materials: ["Algodão"],
    careInstructions: [
      "Lavar à máquina em água fria",
      "Secar em temperatura baixa",
    ],
    reviews: [
      {
        id: 17,
        userId: 555,
        rating: 4.7,
        comment: "Adorei as estampas desta camiseta!",
        createdAt: new Date(),
      },
      {
        id: 18,
        userId: 666,
        rating: 4.5,
        comment: "Muito confortável de usar.",
        createdAt: new Date(),
      },
    ],
    rating: 4.6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    name: "Tênis All Star Chuck Taylor",
    brand: "Converse",
    price: 59.99,
    oldPrice: 69.99,
    sizes: ["38", "39", "40", "41", "42"],
    color: ["black"],
    category: "Tênis",
    gender: "Unisex",
    inStock: true,
    description:
      "Os tênis All Star Chuck Taylor da Converse são um ícone da moda urbana. Este modelo clássico em preto é perfeito para qualquer ocasião. Com seu design atemporal e conforto excepcional, esses tênis são ideais para uso diário. A parte superior de lona durável e a sola de borracha proporcionam durabilidade e tração. Os All Star são conhecidos por seu estilo versátil e são facilmente combinados com roupas casuais. Adquira este par de tênis e faça uma declaração de estilo autêntica.",
    image: "/images/product-09.jpg",
    materials: ["Lona", "Borracha"],
    careInstructions: ["Limpe com um pano úmido", "Não mergulhe na água"],
    reviews: [
      {
        id: 19,
        userId: 777,
        rating: 4.9,
        comment: "Tênis confortáveis e duráveis, um clássico!",
        createdAt: new Date(),
      },
      {
        id: 20,
        userId: 888,
        rating: 4.7,
        comment: "Sempre adorei os All Star, e esses não decepcionam.",
        createdAt: new Date(),
      },
    ],
    rating: 4.8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    name: "Camiseta Feminina Preta Básica",
    brand: "Essential Wear",
    price: 19.99,
    oldPrice: 24.99,
    sizes: ["S", "M", "L", "XL"],
    color: ["black"],
    category: "Camisetas",
    gender: "F",
    inStock: true,
    description:
      "Esta camiseta feminina preta é uma peça básica essencial para o seu guarda-roupa. Com um design minimalista, esta camiseta é versátil e pode ser combinada com várias peças de roupa. Feita com algodão macio de alta qualidade, oferece conforto durante todo o dia. O corte moderno proporciona um ajuste perfeito. Use-a como base para criar looks casuais ou adicione acessórios para um toque de estilo. Cuide dela lavando à máquina em água fria e secando em temperatura baixa. Adquira esta camiseta preta e tenha uma peça versátil em seu guarda-roupa.",
    image: "/images/product-10.jpg",
    materials: ["Algodão"],
    careInstructions: [
      "Lavar à máquina em água fria",
      "Secar em temperatura baixa",
    ],
    reviews: [
      {
        id: 21,
        userId: 111,
        rating: 4.6,
        comment: "Uma camiseta básica de alta qualidade.",
        createdAt: new Date(),
      },
      {
        id: 22,
        userId: 222,
        rating: 4.4,
        comment: "Ótimo custo-benefício, muito confortável.",
        createdAt: new Date(),
      },
    ],
    rating: 4.5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 11,
    name: "Camisa Xadrez Azul Masculina",
    brand: "Checkered Style",
    price: 39.99,
    oldPrice: 49.99,
    sizes: ["S", "M", "L", "XL"],
    color: ["blue", "white"],
    category: "Camisas",
    gender: "M",
    inStock: true,
    description:
      "Esta camisa xadrez azul masculina é a escolha perfeita para um visual casual e descontraído. O padrão xadrez em tons de azul e branco adiciona um toque de estilo à sua roupa. Feita com algodão de alta qualidade, esta camisa oferece conforto durante todo o dia. Ela combina perfeitamente com jeans ou bermudas para um look descontraído e moderno. Cuide dela lavando à máquina em água fria e secando em temperatura baixa. Adquira esta camisa xadrez para um visual despojado e elegante.",
    image: "/images/product-11.jpg",
    materials: ["Algodão"],
    careInstructions: [
      "Lavar à máquina em água fria",
      "Secar em temperatura baixa",
    ],
    reviews: [
      {
        id: 23,
        userId: 333,
        rating: 4.7,
        comment: "Adorei o estilo desta camisa xadrez.",
        createdAt: new Date(),
      },
      {
        id: 24,
        userId: 444,
        rating: 4.5,
        comment: "Confortável de usar e ótima qualidade.",
        createdAt: new Date(),
      },
    ],
    rating: 4.6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 12,
    name: "Cinto de Couro Marrom",
    brand: "LeatherCraft",
    price: 34.99,
    oldPrice: 44.99,
    sizes: ["S", "M", "L", "XL"],
    color: ["brown"],
    category: "Cintos",
    gender: "Unisex",
    inStock: true,
    description:
      "Este cinto de couro marrom é uma adição elegante ao seu guarda-roupa. Feito com couro genuíno de alta qualidade, este cinto oferece durabilidade e estilo atemporal. A fivela metálica polida adiciona um toque de sofisticação. Use este cinto para acentuar sua cintura e dar um toque final ao seu look. Ele combina perfeitamente com calças, jeans ou saias. Cuide dele limpando com um pano úmido e evite a exposição prolongada ao sol. Adquira este cinto de couro marrom e adicione um toque clássico ao seu estilo.",
    image: "/images/product-12.jpg",
    materials: ["Couro Genuíno", "Metal"],
    careInstructions: [
      "Limpe com um pano úmido",
      "Evite exposição prolongada ao sol",
    ],
    reviews: [
      {
        id: 25,
        userId: 555,
        rating: 4.8,
        comment: "Cinto de couro de alta qualidade, estou muito satisfeito.",
        createdAt: new Date(),
      },
      {
        id: 26,
        userId: 666,
        rating: 4.6,
        comment: "A fivela é muito elegante, adoro este cinto.",
        createdAt: new Date(),
      },
    ],
    rating: 4.7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 13,
    name: "Calça Jeans Feminina Skinny",
    brand: "Denim Diva",
    price: 49.99,
    oldPrice: 59.99,
    sizes: ["24", "26", "28", "30", "32"],
    color: ["blue"],
    category: "Calças",
    gender: "F",
    inStock: true,
    description:
      "Esta calça jeans feminina skinny é perfeita para quem procura estilo e conforto. Feita com denim de alta qualidade, esta calça oferece um ajuste perfeito e durabilidade. O corte skinny valoriza a silhueta e combina facilmente com diferentes blusas e calçados. Use-a para criar looks casuais ou adicione acessórios para uma abordagem mais elegante. Cuide dela lavando à máquina em água fria e secando em temperatura baixa. Adquira esta calça jeans e tenha uma peça versátil em seu guarda-roupa.",
    image: "/images/product-13.jpg",
    materials: ["Denim"],
    careInstructions: [
      "Lavar à máquina em água fria",
      "Secar em temperatura baixa",
    ],
    reviews: [
      {
        id: 27,
        userId: 777,
        rating: 4.7,
        comment: "A calça jeans perfeita para qualquer ocasião!",
        createdAt: new Date(),
      },
      {
        id: 28,
        userId: 888,
        rating: 4.5,
        comment: "Confortável e estilosa, estou muito satisfeita.",
        createdAt: new Date(),
      },
    ],
    rating: 4.6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 14,
    name: "Camiseta Floral Feminina",
    brand: "FlowerBloom",
    price: 29.99,
    oldPrice: 39.99,
    sizes: ["S", "M", "L", "XL"],
    color: ["floral pattern"],
    category: "Camisetas",
    gender: "F",
    inStock: true,
    description:
      "Esta camiseta floral feminina é perfeita para adicionar um toque de frescor e cor ao seu guarda-roupa. O padrão floral elegante é ideal para a primavera e o verão. Feita com algodão macio de alta qualidade, esta camiseta oferece conforto durante todo o dia. O corte moderno garante um ajuste perfeito. Use-a com shorts, saias ou jeans para criar um visual descontraído e alegre. Cuide dela lavando à máquina em água fria e secando em temperatura baixa. Adquira esta camiseta floral e traga a natureza para o seu estilo.",
    image: "/images/product-14.jpg",
    materials: ["Algodão"],
    careInstructions: [
      "Lavar à máquina em água fria",
      "Secar em temperatura baixa",
    ],
    reviews: [
      {
        id: 29,
        userId: 999,
        rating: 4.8,
        comment:
          "A estampa floral é linda, estou apaixonada por esta camiseta.",
        createdAt: new Date(),
      },
      {
        id: 30,
        userId: 888,
        rating: 4.6,
        comment: "Muito confortável de usar, ótima para dias quentes.",
        createdAt: new Date(),
      },
    ],
    rating: 4.7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 15,
    name: "Relógio de Malha Prateada",
    brand: "Silver Elegance",
    price: 79.99,
    oldPrice: 99.99,
    color: ["silver"],
    category: "Relógios",
    gender: "Unisex",
    inStock: true,
    description:
      "Este relógio de malha prateada é uma combinação perfeita de estilo e sofisticação. O design minimalista com uma pulseira de malha prateada e mostrador branco torna este relógio uma escolha elegante. O movimento preciso garante que você esteja sempre no horário. A caixa e a pulseira de aço inoxidável oferecem durabilidade e um toque moderno. Este relógio é adequado para ocasiões formais ou uso diário. Cuide dele mantendo-o limpo com um pano macio. Adquira este relógio de malha prateada e eleve o seu estilo.",
    image: "/images/product-15.jpg",
    materials: ["Aço Inoxidável"],
    waterResistance: "Resistente a respingos de água",
    reviews: [
      {
        id: 31,
        userId: 777,
        rating: 4.9,
        comment: "Um relógio elegante que combina com tudo.",
        createdAt: new Date(),
      },
      {
        id: 32,
        userId: 888,
        rating: 4.7,
        comment: "Ótima qualidade, estou muito satisfeito.",
        createdAt: new Date(),
      },
    ],
    rating: 4.8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 16,
    name: "Camiseta Feminina de Gola Aberta",
    brand: "Open Neck Couture",
    price: 34.99,
    oldPrice: 44.99,
    sizes: ["S", "M", "L", "XL"],
    color: ["grey"],
    category: "Camisetas",
    gender: "F",
    inStock: true,
    description:
      "Esta camiseta feminina de gola aberta é perfeita para um visual casual e elegante. A gola bem aberta adiciona um toque moderno ao seu estilo. Feita com algodão macio de alta qualidade, esta camiseta oferece conforto durante todo o dia. O corte moderno garante um ajuste perfeito. Use-a com jeans, shorts ou saias para criar um look descontraído e sofisticado. Cuide dela lavando à máquina em água fria e secando em temperatura baixa. Adquira esta camiseta de gola aberta e faça uma declaração de moda única.",
    image: "/images/product-16.jpg",
    materials: ["Algodão"],
    careInstructions: [
      "Lavar à máquina em água fria",
      "Secar em temperatura baixa",
    ],
    reviews: [
      {
        id: 33,
        userId: 111,
        rating: 4.8,
        comment: "Adoro a gola aberta desta camiseta, muito estilosa.",
        createdAt: new Date(),
      },
      {
        id: 34,
        userId: 222,
        rating: 4.6,
        comment: "Confortável e elegante, uma ótima escolha.",
        createdAt: new Date(),
      },
    ],
    rating: 4.7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
