// import { ClothingCategory, ClothingItem, Gender } from "@/interfaces/Clothes";

export const productsData: any[] = [
  {
    id: 1,
    name: "Vestido de Algodão",
    brand: "ABC Vestuário",
    price: 29.99,
    oldPrice: 123.0,
    sizes: ["S", "M", "L"],
    color: ["white"],
    category: "Tops",
    gender: "F",
    inStock: true,
    description:
      "Descubra o conforto e a elegância em um vestido de algodão feito sob medida para seu dia a dia. Este vestido branco é perfeito para qualquer ocasião, seja um encontro casual ou um passeio no parque. Seu design versátil combina com seu estilo único e oferece a comodidade que você merece. Feito com materiais de alta qualidade, incluindo algodão macio, garantindo durabilidade e conforto. Cuide dele lavando à máquina em água fria e secando em temperatura baixa. Não perca a oportunidade de adicionar esta peça essencial ao seu guarda-roupa. Seja você mesma, com ABC Vestuário.",
    image: "/images/product-01.jpg",
    materials: ["Algodão"],
    careInstructions: [
      "Lavar à máquina em água fria",
      "Secar em temperatura baixa",
    ],
    reviews: [
      {
        id: 1,
        userId: 123,
        rating: 4.5,
        comment: "Vestido de ótima qualidade!",
        createdAt: new Date(),
      },
      {
        id: 2,
        userId: 456,
        rating: 3.8,
        comment: "Fica um pouco pequeno.",
        createdAt: new Date(),
      },
    ],
    rating: 4.2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    name: "Slim Fit Jeans",
    brand: "XYZ Denim",
    price: 49.99,
    oldPrice: 123.0,
    image: "/images/product-02.jpg",
    sizes: ["28", "30", "32", "34"],
    color: ["blue"],
    category: "Bottoms",
    gender: "Male",
    inStock: true,
    description: "Classic slim fit jeans for a stylish look.",
    materials: ["Cotton", "Spandex"],
    careInstructions: ["Machine wash cold", "Do not bleach", "Iron low"],
    reviews: [
      {
        id: 3,
        userId: 789,
        rating: 4.7,
        comment: "Perfect fit!",
        createdAt: new Date(),
      },
      {
        id: 4,
        userId: 456,
        rating: 4.2,
        comment: "Nice quality denim.",
        createdAt: new Date(),
      },
    ],
    rating: 4.5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    name: "Canvas Sneakers",
    brand: "DEF Footwear",
    price: 39.99,
    oldPrice: 123.0,
    image: "/images/product-03.jpg",
    sizes: ["US 6", "US 7", "US 8", "US 9"],
    color: ["white"],
    category: "Shoes",
    gender: "Unisex",
    inStock: true,
    description: "Casual canvas sneakers for everyday wear.",
    materials: ["Canvas", "Rubber"],
    careInstructions: ["Spot clean", "Air dry"],
    reviews: [
      {
        id: 5,
        userId: 123,
        rating: 4.9,
        comment: "Love these sneakers!",
        createdAt: new Date(),
      },
      {
        id: 6,
        userId: 789,
        rating: 4.5,
        comment: "Comfortable and stylish.",
        createdAt: new Date(),
      },
    ],
    rating: 4.7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    name: "Canvas Sneakers",
    brand: "DEF Footwear",
    price: 39.99,
    oldPrice: 123.0,
    image: "/img/product-4.jpg",
    sizes: ["US 6", "US 7", "US 8", "US 9"],
    color: ["white"],
    category: "Shoes",
    gender: "Unisex",
    inStock: true,
    description: "Casual canvas sneakers for everyday wear.",
    materials: ["Canvas", "Rubber"],
    careInstructions: ["Spot clean", "Air dry"],
    reviews: [
      {
        id: 5,
        userId: 123,
        rating: 4.9,
        comment: "Love these sneakers!",
        createdAt: new Date(),
      },
      {
        id: 6,
        userId: 789,
        rating: 4.5,
        comment: "Comfortable and stylish.",
        createdAt: new Date(),
      },
    ],
    rating: 4.7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    name: "Slim Fit Jeans",
    brand: "XYZ Denim",
    price: 49.99,
    oldPrice: 123.0,
    image: "/img/product-5.jpg",
    sizes: ["28", "30", "32", "34"],
    color: ["blue"],
    category: "Bottoms",
    gender: "Male",
    inStock: true,
    description: "Classic slim fit jeans for a stylish look.",
    materials: ["Cotton", "Spandex"],
    careInstructions: ["Machine wash cold", "Do not bleach", "Iron low"],
    reviews: [
      {
        id: 3,
        userId: 789,
        rating: 4.7,
        comment: "Perfect fit!",
        createdAt: new Date(),
      },
      {
        id: 4,
        userId: 456,
        rating: 4.2,
        comment: "Nice quality denim.",
        createdAt: new Date(),
      },
    ],
    rating: 4.5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    name: "Canvas Sneakers",
    brand: "DEF Footwear",
    price: 39.99,
    oldPrice: 123.0,
    image: "/img/product-6.jpg",
    sizes: ["US 6", "US 7", "US 8", "US 9"],
    color: ["white"],
    category: "Shoes",
    gender: "Unisex",
    inStock: true,
    description: "Casual canvas sneakers for everyday wear.",
    materials: ["Canvas", "Rubber"],
    careInstructions: ["Spot clean", "Air dry"],
    reviews: [
      {
        id: 5,
        userId: 123,
        rating: 4.9,
        comment: "Love these sneakers!",
        createdAt: new Date(),
      },
      {
        id: 6,
        userId: 789,
        rating: 4.5,
        comment: "Comfortable and stylish.",
        createdAt: new Date(),
      },
    ],
    rating: 4.7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    name: "Canvas Sneakers",
    brand: "DEF Footwear",
    price: 39.99,
    oldPrice: 123.0,
    image: "/img/product-7.jpg",
    sizes: ["US 6", "US 7", "US 8", "US 9"],
    color: ["white"],
    category: "Shoes",
    gender: "Unisex",
    inStock: true,
    description: "Casual canvas sneakers for everyday wear.",
    materials: ["Canvas", "Rubber"],
    careInstructions: ["Spot clean", "Air dry"],
    reviews: [
      {
        id: 5,
        userId: 123,
        rating: 4.9,
        comment: "Love these sneakers!",
        createdAt: new Date(),
      },
      {
        id: 6,
        userId: 789,
        rating: 4.5,
        comment: "Comfortable and stylish.",
        createdAt: new Date(),
      },
    ],
    rating: 4.7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    name: "Cotton T-Shirt",
    brand: "ABC Apparel",
    price: 29.99,
    oldPrice: 123.0,
    sizes: ["S", "M", "L"],
    color: ["black"],
    category: "Tops",
    gender: "Unisex",
    inStock: true,
    description: "A comfortable cotton t-shirt for everyday wear.",
    image: "/img/product-8.jpg",
    materials: ["Cotton"],
    careInstructions: ["Machine wash cold", "Tumble dry low"],
    reviews: [
      {
        id: 1,
        userId: 123,
        rating: 4.5,
        comment: "Great quality shirt!",
        createdAt: new Date(),
      },
      {
        id: 2,
        userId: 456,
        rating: 3.8,
        comment: "Runs slightly small.",
        createdAt: new Date(),
      },
    ],
    rating: 4.2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const dataList = [
  {
    text: "Laptops",
    link: "/shop?c=Laptops",
  },
  {
    text: "Smartphones",
    link: "/shop?c=Smartphones",
  },
  {
    text: "Câmeras",
    link: "/shop?c=Câmeras",
  },
  {
    text: "Acessórios",
    link: "/shop?c=Acessórios",
  },
];
